name: 2. Apply Version Update

on:
  repository_dispatch:
    types: [update-version]

permissions:
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write version.json
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          cat > version.json <<EOF
          {
            "latest_version_code": ${VERSION},
            "download_url": "https://github.com/Corey935xx/SpotifyVisualizer/releases/latest/download/SpotifyVisualizer.apk"
          }
          EOF

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: update version.json to version ${{ github.event.client_payload.version }}"
          file_pattern: 'version.json'
          branch: main
